name: Pronouns
version: '${project.version}'
main: connorcogged.pronouns.Pronouns
api-version: 1.20
authors: [ Connorcogged ]
description: A plugin that allows users to customzie their pronouns!
website: github.connorcogged.com
